# Source global definitions if they're there
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ll='ls -la'

export EDITOR=vim

# Set prompt
export MY_PROMPT="docker"
export MY_COLOUR="\001\e[0;49;36m\002"

PS1="$MY_COLOUR$MY_PROMPT\001\e[m\002 \W> \[\033[00m\]"
export PS1
